apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2020-12-29T23-29-29Z
          command:
            - minio
          args:
            - server
            - /home/shared
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ROOT_USER_FILE
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD_FILE
              value: minioadmin
            - name: MINIO_KMS_SECRET_KEY_FILE
              value: "minio-encryption-key:minio-encryption-key"
          ports:
            - containerPort: 9000
              protocol: TCP
              name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: spinnaker
spec:
  selector:
    name: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
